# Generated by Django 4.1.3 on 2022-11-22 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Resource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.IntegerField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("VCR", "Video Conference Room"),
                            ("MR", "Meeting Room"),
                            ("240S", "240 Seater"),
                            ("120-A", "120 Seater Room-1"),
                            ("120-B", "120 Seater Room-2"),
                            ("PMR", "Personal Meeting Room"),
                        ],
                        max_length=5,
                    ),
                ),
                ("capacity", models.IntegerField()),
                ("seats", models.IntegerField()),
            ],
        ),
    ]
