# Generated by Django 4.1.3 on 2022-11-22 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduling", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="user_detail",
            fields=[
                ("username", models.CharField(max_length=100, null=True)),
                (
                    "email",
                    models.EmailField(
                        max_length=254, primary_key=True, serialize=False
                    ),
                ),
                ("password", models.CharField(max_length=50)),
                ("confirm_password", models.CharField(max_length=50)),
                ("mobile_number", models.CharField(max_length=14)),
            ],
        ),
    ]
