# Generated by Django 4.1.3 on 2022-11-24 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduling", "0002_user_detail"),
    ]

    operations = [
        migrations.CreateModel(
            name="Booking_detail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fullname", models.CharField(max_length=100, null=True)),
                ("date", models.DateField()),
                (
                    "slot",
                    models.CharField(
                        choices=[
                            ("1hr", "1 Hour"),
                            ("2hr", "2 Hour"),
                            ("3hr", "3 Hour"),
                            ("4hr+", "4 Hour +"),
                        ],
                        max_length=4,
                    ),
                ),
                ("start", models.TimeField()),
                (
                    "start_parity",
                    models.CharField(
                        choices=[("AM", "AM"), ("PM", "PM")], max_length=2
                    ),
                ),
                ("end", models.TimeField()),
                (
                    "end_parity",
                    models.CharField(
                        choices=[("AM", "AM"), ("PM", "PM")], max_length=2
                    ),
                ),
                ("description", models.TextField()),
            ],
        ),
    ]
