# Generated by Django 4.1.3 on 2022-11-24 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduling", "0003_booking_detail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking_detail",
            name="slot",
            field=models.CharField(
                choices=[
                    ("1hr", "1 Hour"),
                    ("2hr", "2 Hour"),
                    ("3hr", "3 Hour"),
                    ("4hr+", "4 Hour +"),
                ],
                max_length=5,
            ),
        ),
    ]
