# Generated by Django 4.1.3 on 2022-11-24 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduling", "0004_alter_booking_detail_slot"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking_detail",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
